# Fork the repository instead of creating a new branch on the same owner.
### Needed to operate on repositories where you don't have enought permissions
fork: true

# If set, make the fork to the defined value. Default behavior is for the fork to be on the logged in user.
### Set to a test organisation to not polute your GitHub profile with many forks
# fork-owner: jenkins-docs

# Comment or set to false the following line to run the script for real
# dry-run: true

# # # The name, including owner of a GitHub repository in the format "ownerName/repoName".
repo:
  # - jenkinsci/schedule-build-plugin
  # - jenkinsci/testng-plugin-plugin
  # - jenkinsci/priority-sorter-plugin
  # - jenkinsci/nodelabelparameter-plugin
  # - jenkinsci/apache-httpcomponents-client-4-api-plugin
  # - jenkinsci/lockable-resources-plugin
  # - jenkinsci/jaxb-plugin
  # - jenkinsci/windows-slaves-plugin
  # - jenkinsci/run-condition-plugin
  # - jenkinsci/parameterized-trigger-plugin
  # - jenkinsci/conditional-buildstep-plugin
  - jenkinsci/mercurial-plugin
  # - jenkinsci/gitlab-plugin
  # - jenkinsci/docker-java-api-plugin
  # - jenkinsci/docker-plugin
  # - jenkinsci/cvs-plugin
  # - jenkinsci/authorize-project-plugin
  # - jenkinsci/http-request-plugin
  # - jenkinsci/emailext-template-plugin
  # - jenkinsci/msbuild-plugin
  - jenkinsci/badge-plugin
  # - jenkinsci/gitlab-oauth-plugin
  # - jenkinsci/build-timestamp-plugin
  # - jenkinsci/github-oauth-plugin
  # - jenkinsci/configurationslicing-plugin
  # - jenkinsci/promoted-builds-plugin
  # - jenkinsci/m2release-plugin
  # - jenkinsci/disk-usage-plugin
  # - jenkinsci/global-build-stats-plugin
  # - jenkinsci/test-results-analyzer-plugin
  # - jenkinsci/backup-plugin
  # - jenkinsci/artifactdeployer-plugin
  # - jenkinsci/plot-plugin
  # - jenkinsci/versionnumber-plugin
  # - jenkinsci/job-restrictions-plugin
  # - jenkinsci/kubernetes-cd-plugin
